# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkE5j8o2RIC6-m82wXJP3iLgKvboOwQw
"""

print("Hello World")
name = input("What is your Name?")
print(f"Nice to meet you {name}")